name: ocm-resources
run-name: Build component version using resources.yaml
on:
  workflow_dispatch:
  push:
    branches:
      - main
env:
  COMP_NAME: acme.org/podinfo
  PROVIDER: github.com/linuxbsdfreak
  CD_REPO: ghcr.io/linuxbsdfreak/ocm
  OCI_URL: ghcr.io/linuxbsdfreak
jobs:
  build-and-create-ocm:
    runs-on: ubuntu-latest
    steps:
      - name: Check out the repo
        uses: actions/checkout@v3
      - name: setup OCM
        uses: open-component-model/ocm-setup-action@main
      - name: Set up QEMU
        uses: docker/setup-qemu-action@v2
      - name: Set up Docker Context for Buildx
        id: buildx-context
        run: |
          docker context create builders
      - name: Set up Docker Buildx
        timeout-minutes: 5
        uses: docker/setup-buildx-action@v2
        with:
          version: latest
      - name: Get version from file
        run: |
          version=`cat VERSION`
          echo "VERSION=$version" >> $GITHUB_ENV
          echo "Using version: $version"
      - name: Build amd64
        id: build_amd64
        uses: docker/build-push-action@v3
        with:
          push: false
          load: true
          platforms: linux/amd64
          tags: ${{ env.OCI_URL }}/${{ env.COMP_NAME }}:${{ env.VERSION }}-linux-amd64
      - name: Build arm64
        id: build_arm64
        uses: docker/build-push-action@v3
        with:
          push: false
          load: true
          platforms: linux/arm64
          tags: ${{ env.OCI_URL }}/${{ env.COMP_NAME }}:${{ env.VERSION }}-linux-arm64
      - name: create OCM component version
        uses: open-component-model/ocm-action@main
        with:
          action: create_component
          component: ${{ env.COMP_NAME }}
          provider: ${{ env.PROVIDER }}
          version: ${{ env.VERSION }}
      - name: add OCM resources
        uses: open-component-model/ocm-action@main
        with:
          action: add_resources
          component: ${{ env.COMP_NAME }}
          resources: ./../../ocm/resources.yaml
          version: ${{ env.VERSION }}
          # Note below that you have to use double quotes for the VARIANTS value.
          var_values: |
            IMAGE: ${{ env.OCI_URL }}/${{ env.COMP_NAME }}
            VARIANTS: "['${{ env.OCI_URL }}/${{ env.COMP_NAME }}:${{ env.VERSION }}-linux-amd64', '${{ env.OCI_URL }}/${{ env.COMP_NAME }}:${{ env.VERSION }}-linux-arm64']"
      - name: create OCM transport archive
        uses: open-component-model/ocm-action@main
        with:
          action: add_component
      - name: push OCM transport archive
        uses: open-component-model/ocm-action@main
        with:
          action: push_ctf
          # Warning: use force_push only for development (overwrites existing components)!
          force_push: true
          comprepo_password: ${{ secrets.GITHUB_TOKEN }}
          comprepo_url: ${{ env.CD_REPO }}
      - name: Upload transport archive
        uses: actions/upload-artifact@v3
        with:
          name: ocm-simpleserver-ctf.zip
          path: |
            gen/ocm/ctf
